site_name: Home - UNL UAV
nav:
  - Home: index.md
  - Getting Started: welcome.md
  - Teams: teams.md
  - People: people.md
  - Creating Documentation: creating_docs.md
  - Resources: resources.md
  - Credits: credits.md
theme: readthedocs
site_description: UNL Aerospace UAV IARC Team Page
markdown_extensions:
  - attr_list