site_name: UNL UAV
nav:
  - Home: index.md
  - Teams: teams.md
  - People: people.md
  - Creating Documentation: creating_docs.md
  - Resources: resources.md
  - Credits: credits.md
theme: readthedocs
